env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    "linebreak-style": [0, "error", "windows"],
    "indent": ["error", 4],
    "import/extensions": ["error", { "js": "ignorePackages" }],
  }
